CREATE SCHEMA "thesis";
--> statement-breakpoint
CREATE TABLE "thesis"."permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "thesis"."permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar,
	"slug" varchar,
	"description" varchar,
	"date_created" timestamp,
	CONSTRAINT "permission_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "thesis"."roles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "thesis"."roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar,
	"slug" varchar,
	"description" varchar,
	"date_created" timestamp,
	CONSTRAINT "roles_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "thesis"."users" (
	"id" uuid PRIMARY KEY NOT NULL,
	"email" varchar,
	"password" varchar,
	"date_created" timestamp,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
