CREATE TABLE "thesis"."references_summary" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "thesis"."references_summary_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"summaryId" integer,
	"fileId" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "thesis"."summaries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "thesis"."summaries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"subjectId" integer,
	"themeId" integer,
	"fileId" uuid NOT NULL
);
--> statement-breakpoint
ALTER TABLE "thesis"."references_summary" ADD CONSTRAINT "references_summary_summaryId_summaries_id_fk" FOREIGN KEY ("summaryId") REFERENCES "thesis"."summaries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "thesis"."references_summary" ADD CONSTRAINT "references_summary_fileId_files_id_fk" FOREIGN KEY ("fileId") REFERENCES "thesis"."files"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "thesis"."summaries" ADD CONSTRAINT "summaries_subjectId_subjects_id_fk" FOREIGN KEY ("subjectId") REFERENCES "thesis"."subjects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "thesis"."summaries" ADD CONSTRAINT "summaries_themeId_themes_id_fk" FOREIGN KEY ("themeId") REFERENCES "thesis"."themes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "thesis"."summaries" ADD CONSTRAINT "summaries_fileId_files_id_fk" FOREIGN KEY ("fileId") REFERENCES "thesis"."files"("id") ON DELETE no action ON UPDATE no action;