CREATE TABLE "thesis"."references_faq" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "thesis"."references_faq_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"faqId" uuid,
	"fileId" uuid NOT NULL
);
--> statement-breakpoint
ALTER TABLE "thesis"."references_faq" ADD CONSTRAINT "references_faq_faqId_faqs_id_fk" FOREIGN KEY ("faqId") REFERENCES "thesis"."faqs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "thesis"."references_faq" ADD CONSTRAINT "references_faq_fileId_files_id_fk" FOREIGN KEY ("fileId") REFERENCES "thesis"."files"("id") ON DELETE no action ON UPDATE no action;